# Generated by Django 4.2.1 on 2024-07-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
