# Generated by Django 4.2.1 on 2024-07-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_application_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicant',
            new_name='applicant_name',
        ),
    ]
