# Generated by Django 4.2.1 on 2024-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_application_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
