# Generated by Django 4.2.1 on 2024-07-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_alter_application_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
