# Generated by Django 4.2.1 on 2024-07-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_application_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='age',
            new_name='p_age',
        ),
    ]
