# Generated by Django 4.2.1 on 2024-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_rename_age_application_p_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
