# Generated by Django 4.2.1 on 2024-07-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_application_age'),
    ]

    operations = [
    ]
