# Generated by Django 4.2.1 on 2024-07-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_auto_20240705_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='age',
        ),
    ]
