# Generated by Django 4.2.1 on 2024-07-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_remove_application_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='p_age',
            new_name='age',
        ),
    ]
